---
version: '3.8'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: secrets
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
